# Generated by Django 5.0.6 on 2024-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investstudies',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cards-img/'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cards-img/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(null=True, upload_to='cards-img/'),
        ),
    ]
