# Generated by Django 5.0.6 on 2024-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_to_jatos',
            field=models.URLField(default=''),
        ),
    ]
