# Generated by Django 5.0.6 on 2025-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_aboutuscontenttranslation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefavicon',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='favico-img/'),
        ),
    ]
