# Generated by Django 5.0.6 on 2024-10-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_investstudies_photo_alter_scale_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cards-img/'),
        ),
    ]
