# Generated by Django 5.0.6 on 2025-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_imagefavicon_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktranslation',
            name='general_info',
            field=models.TextField(default='', verbose_name='Información General'),
        ),
    ]
