# Generated by Django 5.0.6 on 2024-10-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_task_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investstudies',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
