# Generated by Django 5.0.6 on 2024-06-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_task_project_recommended_alter_project_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='recommended',
            new_name='is_recommended',
        ),
    ]
