# Generated by Django 5.0.6 on 2024-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_investstudies_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFavicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_img', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='cards-img/')),
            ],
        ),
    ]
