# Generated by Django 5.0.6 on 2025-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_tasktranslation_general_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktranslation',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, verbose_name='Dificultad'),
        ),
        migrations.AddField(
            model_name='tasktranslation',
            name='process_to_evaluate',
            field=models.TextField(default='', verbose_name='Procesos a evaluar'),
        ),
        migrations.AddField(
            model_name='tasktranslation',
            name='recommended_age',
            field=models.PositiveIntegerField(default=1, verbose_name='Edad Recomendada'),
        ),
    ]
