# Generated by Django 5.0.6 on 2024-06-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_recommended_project_is_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='recommended',
            new_name='is_recommended',
        ),
    ]
