# Generated by Django 5.0.6 on 2024-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_recommended_task_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(default='')),
                ('x_twitter', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('threads', models.URLField(default='')),
                ('youtube', models.URLField(default='')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='cards-img/')),
                ('privacy_url', models.URLField(default='')),
                ('cookies_policy', models.URLField(default='')),
            ],
        ),
    ]
