# Generated by Django 5.0.6 on 2024-06-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_footerbanners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterBanners',
            new_name='FooterBanner',
        ),
    ]
