# Generated by Django 5.0.6 on 2024-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_rename_footerbanners_footerbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerbanner',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='threads',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='x_twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
