# Generated by Django 5.0.6 on 2024-07-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_footerbanner_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ca',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name_ca',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name_es',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
