# Generated by Django 5.0.6 on 2024-07-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_project_description_ca_project_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_es',
        ),
    ]
