# Generated by Django 5.1.1 on 2024-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='cards-img/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
